# frozen_string_literal: true

PreCommit:
  Rubocop:
    enabled: true
    on_warn: fail

  BundleAudit:
    enabled: true
  
  Fasterer:
    enabled: true

  TrailingWhitespace:
    enabled: false
    exclude:
      - '**/db/structure.sql'

  EsLint:
    enabled: false
    on_warn: warn

  ScssLint:
    enabled: true
    on_warn: warn

CommitMsg:
  TextWidth:
    enabled: true

  CapitalizedSubject:
    enabled: true

PostCheckout:
  ALL:
    quiet: true

  IndexTags:
    enabled: true

PostMerge:
  BundleInstall:
    enabled: true

PostRewrite:
  ALL:
    quiet: true

PrePush:
  CheckCoverage:
    enabled: true
    description: 'Checking code coverage'
    command: ['sh', 'scripts/check_coverage.sh']