# frozen_string_literal: true

PreCommit:
  Rubocop:
    enabled: true
    on_warn: fail

  BundleAudit:
    enabled: true
  
  Fasterer:
    enabled: true

  TrailingWhitespace:
    enabled: false
    exclude:
      - '**/db/structure.sql'

  EsLint:
    enabled: false # Change this to `true` if you want to enable ESLint
    on_warn: warn

  ScssLint:
    enabled: true
    on_warn: warn

CommitMsg:
  TextWidth:
    enabled: true

  CapitalizedSubject:
    enabled: true

PostCheckout:
  ALL:
    quiet: true

  IndexTags:
    enabled: true

PostMerge:
  BundleInstall:
    enabled: true

PostRewrite:
  ALL:
    quiet: true