  version: '3'
  services:
    # Database
    db:
      image: postgres
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - "5432:5432"

    # Web Application
    web:
      build: .
      command: rails s -p 3000 -b '0.0.0.0'
      volumes:
        - .:/usr/src/app
      ports:
        - "3000:3000"
      depends_on:
        - db
      environment:
        - RAILS_ENV=development
        - DATABASE_HOST=${DB_HOST}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
      stdin_open: true
      tty: true

    # Nginx
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./balancers/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - web

    # Haproxy:
    #   image: haproxy:latest
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./balancers/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    #   depends_on:
    #     - web

  volumes:
    postgres-data: