# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME')%>_development

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>_production
  url: <%= ENV['DATABASE_URL'] %>